### ISSUE TITLE
Some .config files have spaces instead of tabs

### ISSUE THREAD

**Issue by lgessler** [CopticScriptorium/corpora#29]
E.g. [analytic.config for shenoute.fox](https://github.com/CopticScriptorium/corpora/blob/master/shenoute-fox/shenoute.fox_ANNIS/ExtData/analytic.config#L4), where "translation" in the first column is followed by a space.

**Comment by amir-zeldes** [comment]
This looks like a bug... I'm surprised it works at all. I've corrected the source files for the vis definitions, so they should update on the next release. Since ANNIS tolerates this, I think we can skip a hotfix release.

Just in case there are other gremlins like this: can you have the repo config reader also tolerate:

  * Space separators for entire line if no tabs are found
  * First separator is space if a line contains a space before it contains a tab but does not contain double quotes?

Explanation: Anno names can't contain spaces so the only legitimate way that tab is the first column separator but the first column contains space is if an anno-value trigger has been used:

```
my_anno="first chapter"\t...
```

**Comment by lgessler** [comment]
I used [a regex that replaces a first space with a tab](https://github.com/lgessler/cts/blob/CTS-dev/coptic/gh_ingest/htmlvis.py#L304L313), and that seemed to solve the issue for all the corpora.

**Comment by amir-zeldes** [comment]
OK thanks, we should still leave this issue open until the source data is fixed (should happen via released 3.0, since config templates have been fixed locally)

**Comment by amir-zeldes** [comment]
Fixed in 31450f6
