### ISSUE TITLE
Morph Errors

### ISSUE THREAD

**Issue by lancealanmartin** [CopticScriptorium/corpora#30]
All corpora need to be checked for ⲣⲙⲙⲟⲁ. Should be ⲣⲙ-ⲙ-ⲟⲁ.

**Comment by ctschroeder** [comment]
Hi. I'm going through some of these issues before publication. I'm not seeing ⲣⲙⲙⲟⲁ in our published corpora. Do you remember where you saw it @lancealanmartin?  Thank you!  https://corpling.uis.georgetown.edu/annis/scriptorium#_q=bm9ybV9ncm91cD0vLirisqPispnispnisp_isoEuKi8&_c=YXBvcGh0aGVnbWF0YS5wYXRydW0sYmVzYS5sZXR0ZXJzLGRvYy5wYXB5cmksam9oYW5uZXMuY2Fub25zLG1hcnR5cmRvbS52aWN0b3IscHNldWRvLnRoZW9waGlsdXMsc2FoaWRpYy5vdCxzYWhpZGljYS4xY29yaW50aGlhbnMsc2FoaWRpY2EubWFyayxzYWhpZGljYS5udCxzaGVub3V0ZS5hMjIsc2hlbm91dGUuYWJyYWhhbSxzaGVub3V0ZS5kaXJ0LHNoZW5vdXRlLmVhZ2VybmVzcyxzaGVub3V0ZS5mb3g&cl=5&cr=5&s=0&l=10&_seg=bm9ybV9ncm91cA

**Comment by lancealanmartin** [comment]
Sorry! I misspelled the word. It should be ⲣⲙⲙⲁⲟ.

**Comment by ctschroeder** [comment]
oh goodness I should have seen that. No worries!
https://corpling.uis.georgetown.edu/annis/scriptorium#_q=bm9ybT0v4rKj4rKZ4rKZ4rKB4rKfLw&_c=YmVzYS5sZXR0ZXJzLHNoZW5vdXRlLmEyMixqb2hhbm5lcy5jYW5vbnMsc2hlbm91dGUuYWJyYWhhbSxzaGVub3V0ZS5lYWdlcm5lc3Msc2hlbm91dGUuZGlydCxzYWhpZGljLm90LGFwb3BodGhlZ21hdGEucGF0cnVtLHNhaGlkaWNhLm50LHNhaGlkaWNhLjFjb3JpbnRoaWFucyxwc2V1ZG8udGhlb3BoaWx1cyxzaGVub3V0ZS5mb3gsc2FoaWRpY2EubWFyayxkb2MucGFweXJpLG1hcnR5cmRvbS52aWN0b3I&cl=5&cr=5&s=0&l=10&_seg=bm9ybV9ncm91cA
1_id	1_span	1_anno_scriptorium::norm_group	meta_title

- [ ] 60164833	ⲛ̄ ⲧ︤ ⲙ︦ⲛ︥ⲧ ⲣ︤ⲙ︥ⲙⲁⲟ̂	ⲛⲧⲙⲛⲧⲣⲙⲙⲁⲟ	On Vigilance
- [ ] 60211023	ⲛⲉ ⲟⲩ ⲣⲙ ⲙⲁⲟ	ⲛⲉⲟⲩⲣⲙⲙⲁⲟ	Apa Johannes Canons: FA143-158
- [ ] 60220008	Ⲛ ⲣⲙ ⲙⲁⲟ	ⲛⲣⲙⲙⲁⲟ	Apa Johannes Canons: MONB.FA 29-30
- [ ] 60220038	ⲙ ⲡ ⲣⲙ ⲙⲁⲟ	ⲙⲡⲣⲙⲙⲁⲟ	Apa Johannes Canons: MONB.FA 29-30
- [ ] 60220315	ⲛ̄ ⲣⲙ ⲙⲁⲟ	ⲛⲣⲙⲙⲁⲟ	Apa Johannes Canons: MONB.FA 29-30
- [ ] 60194604	ⲉ ⲣ ⲣ︤ⲙ︥ⲙⲁⲟ	ⲉⲣⲣⲙⲙⲁⲟ	Some Kinds of People Sift Dirt: GL71-74
- [ ] 43772665	ⲉ ⲧⲉⲥ ⲙⲛⲧ ⲣⲙⲙⲁⲟ	ⲉⲧⲉⲥⲙⲛⲧⲣⲙⲙⲁⲟ	I See Your Eagerness: GL61-63
- [ ] 43777777	ⲡ ⲉ ⲧ ⲛ ⲛⲁ ⲣ ⲣⲙⲙⲁⲟ	ⲡⲉⲧⲛⲛⲁⲣⲣⲙⲙⲁⲟ	I See Your Eagerness: GL 63-70
- [ ] 43778432	ⲛ ⲣⲙⲙⲁⲟ	ⲛⲣⲙⲙⲁⲟ	I See Your Eagerness: GL 63-70
- [ ] 43824190	ⲉ ⲧⲉⲥ ⲙ︤ⲛ︦ⲧ ⲣ︤ⲙ︥ⲙⲁⲟ̂	ⲉⲧⲉⲥⲙⲛⲧⲣⲙⲙⲁⲟ	I See Your Eagerness: XJ 65-76
- [ ] 43829276	ⲡ ⲉⲧ︤ ⲛ︥ ⲛⲁ ⟨ⲣ⟩ ⲣ︤ⲙ︥ⲙ ⟨ⲁ⟩ ⲟ̂	ⲡⲉⲧⲛⲛⲁⲣⲣⲙⲙⲁⲟ	I See Your Eagerness: XJ 77-86
- [ ] 43829937	ⲛ̄ ⲣ︤ⲙ︥ⲙⲁⲟ̂	ⲛⲣⲙⲙⲁⲟ	I See Your Eagerness: XJ 77-86
- [ ] 31510094	ⲉⲣ⳿ ⲣ︤ⲙ︥ⲙⲁⲟ̂	ⲣⲣⲙⲙⲁⲟ	Not Because a Fox Barks: XH 204-216

**Comment by ctschroeder** [comment]
reopening because I'm seeing this in a doc that was run through NLP before v. 3.0 of the NLP tools.  Need to check Johannes corpus texts currently being annotated.

**Comment by lgessler** [comment]
question--when yall correct these errors where do you correct them? ANNIS, GitDox, somewhere else?

**Comment by lancealanmartin** [comment]
Gitdox!

**Comment by ctschroeder** [comment]
Yes GitDox. Changes are not/should not be made directly in ANNIS because threats not the core data that gets archived or edited further in future rounds. 

Sent from my iPhone

**Comment by amir-zeldes** [comment]
The publish script pulls data from GitDox and generates the public corpora repo, which includes relANNIS dumps. Those are then imported into ANNIS, while the TT folder is the basis of the CTS interface. So GitDox is where anything that is not added automatically should be corrected (parses for non-treebanked data and MWE are auto-added during publication, and gold parses live in the UD_Coptic repo)

**Comment by ctschroeder** [comment]
all checked
